services:
  rifasdb:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5430:5432"
    volumes:
      - rifas_data:/var/lib/postgresql/data

volumes:
  rifas_data:
